### ISSUE TITLE
Problem running test code

### ISSUE THREAD

**Issue by ipepe** [aevitas/orion#1]
Hello! I have a problem running a test code:
output:

```
State: Full


ID:             -955988861
Health:         -858993460
Position:       <24,875  5,044674E-44  9,783256E-27>
Team:           1256457671
ObjectCount:    128
```

Exception stack:

```
BlueRain.Common.BlueRainReadException was unhandled
  HResult=-2146233088
  Message=ReadProcessMemory failed! Could not read 4 bytes from 64!
  Source=BlueRain
  StackTrace:
       at BlueRain.ExternalProcessMemory.ReadBytes(IntPtr address, Int32 count, Boolean isRelative)
       at BlueRain.ExternalProcessMemory.Read[T](IntPtr address, Boolean isRelative)
       at Orion.GlobalOffensive.Objects.NativeObject.ReadField[T](Int32 offset) in c:\Users\Patryk\Source\Repos\orion\src\Orion.GlobalOffensive\Orion.GlobalOffensive\Objects\NativeObject.cs:line 61
       at Orion.GlobalOffensive.Objects.NativeObject.ReadField[T](StaticOffsets offset) in c:\Users\Patryk\Source\Repos\orion\src\Orion.GlobalOffensive\Orion.GlobalOffensive\Objects\NativeObject.cs:line 72
       at Orion.GlobalOffensive.Objects.BaseEntity.get_Id() in c:\Users\Patryk\Source\Repos\orion\src\Orion.GlobalOffensive\Orion.GlobalOffensive\Objects\BaseEntity.cs:line 31
       at Orion.GlobalOffensive.Objects.LocalPlayer.<>c__DisplayClass1.<get_Target>b__0(BaseEntity p) in c:\Users\Patryk\Source\Repos\orion\src\Orion.GlobalOffensive\Orion.GlobalOffensive\Objects\LocalPlayer.cs:line 59
       at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
       at Orion.GlobalOffensive.Objects.LocalPlayer.get_Target() in c:\Users\Patryk\Source\Repos\orion\src\Orion.GlobalOffensive\Orion.GlobalOffensive\Objects\LocalPlayer.cs:line 59
       at Orion.GlobalOffensive.Test.Program.Main(String[] args) in c:\Users\Patryk\Source\Repos\orion\src\Orion.GlobalOffensive\Orion.GlobalOffensive.Test\Program.cs:line 47
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 

```

**Comment by aevitas** [comment]
The offsets were outdated due to the double CS:GO patch a couple of days ago. I've updated them now - can you pull the new version and let me know if you still run into the same issue?

**Comment by ipepe** [comment]
I will check it tomorrow :smile:

**Comment by ipepe** [comment]
i updated my fork and still same problem, or maybe I am missing something?

**Comment by aevitas** [comment]
Is this still an issue? The test console runs fine for me as of the latest CSGO update.

**Comment by ipepe** [comment]
My cheat ACC got banned and i dont have time to fiddle with orion. I think that issue was that csgo was updated. It would be good to implement a detector that would report IF offest are good or bad

**Comment by aevitas** [comment]
Fair enough, I'll close this issue then. Thanks for taking the time to get back to me! :+1:
